import './style.scss';

function LegalNotice() {
  return (
    <div className="legalNotice__container">
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos repellendus doloremque, tenetur fugit sunt, impedit soluta exercitationem saepe dolor nesciunt provident! Facilis ipsam earum, recusandae atque neque voluptatibus amet aperiam, quia aut tempore architecto sapiente, est soluta cumque. Fuga qui ab inventore dolor repellendus repellat, expedita fugiat natus tenetur perferendis unde accusantium enim quas esse modi sapiente veritatis, amet iusto veniam maxime! Corrupti asperiores, atque impedit magnam molestiae odit odio! Temporibus deleniti ex impedit aperiam eius accusantium sequi. Consequatur quo nostrum eveniet aperiam accusamus. Ullam architecto ea sunt consectetur in recusandae, ducimus debitis repellat vel itaque atque consequuntur repellendus quasi nam enim rem ut delectus fugit nihil harum voluptatibus odit corrupti veniam cupiditate. Exercitationem blanditiis deserunt sint, impedit repellendus vitae vero iste in velit cupiditate doloremque consectetur veritatis sed totam incidunt. Nemo excepturi, maxime similique mollitia magnam autem cum, reprehenderit quis doloremque reiciendis ad. Error, corporis cum dolorem officiis unde commodi in quidem distinctio rem, magnam fugiat qui et id, sequi vel adipisci magni culpa omnis quam. Laborum earum at natus adipisci, alias sequi unde voluptate quaerat beatae numquam molestiae assumenda dolores minima ullam non nisi voluptatum reprehenderit cum inventore obcaecati vero saepe? Quisquam ipsa corporis alias eveniet deserunt qui libero quas ex, voluptas perspiciatis distinctio, minima molestiae totam tempore! Accusantium libero possimus impedit quas dolor mollitia, omnis blanditiis, quod velit fugit tenetur quibusdam nemo asperiores repellat illo eveniet maxime, totam voluptates esse facilis nobis nulla modi similique! Eius, totam. Quam, temporibus a vero culpa perferendis consectetur dicta commodi architecto, nulla excepturi eos fugit modi. Reiciendis, dolores in cupiditate ipsum nisi iusto, ipsam blanditiis quam quos voluptatibus voluptates sed? Hic, aliquid fugit neque iste modi dignissimos! Nam, repellendus debitis officia eius aspernatur velit, repudiandae officiis exercitationem, numquam ea voluptatum veniam deserunt fugit asperiores architecto omnis et! Fugit eaque quibusdam nesciunt?
    </div>
  );
}

export default LegalNotice;
